# Generated by Django 4.1.7 on 2023-03-13 03:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('studatapages', '0002_courses_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='account',
            field=models.OneToOneField(default=2, on_delete=django.db.models.deletion.CASCADE, to='studatapages.login'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='finance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=5)),
                ('payment', models.BooleanField(default=True)),
                ('stu_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='studatapages.student')),
            ],
        ),
    ]
