# Generated by Django 4.1.6 on 2023-05-04 19:15

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('studatapages', '0003_student_account_finance'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='finance',
            name='stu_id',
        ),
        migrations.RemoveField(
            model_name='student',
            name='account',
        ),
        migrations.RemoveField(
            model_name='student',
            name='past_courses',
        ),
        migrations.AlterModelManagers(
            name='login',
            managers=[
                ('empAuth_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterField(
            model_name='login',
            name='id',
            field=models.PositiveSmallIntegerField(primary_key=True, serialize=False),
        ),
        migrations.DeleteModel(
            name='courses',
        ),
        migrations.DeleteModel(
            name='finance',
        ),
        migrations.DeleteModel(
            name='student',
        ),
    ]
