# Generated by Django 4.1.6 on 2023-05-04 19:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studatapages', '0004_remove_finance_stu_id_remove_student_account_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='login',
        ),
    ]
