# Generated by Django 4.1.6 on 2023-07-01 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studatapages', '0008_alter_login_chours_alter_login_gpa'),
    ]

    operations = [
        migrations.AddField(
            model_name='login',
            name='finance',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
